const produtos = [
  { nome: "Natura Tododia Óleo Bifásico Corporal Cereja e Avelã", categoria: "Corpo e banho", preco: 63.90, imagem: "produto-01.jpg" },
  { nome: "Floratta Romance de Verão", categoria: "Perfumes", preco: 174.90, imagem: "produto-02.jpg" },
  { nome: "Egeo Dolce", categoria: "Perfumes", preco: 164.90, imagem: "produto-03.jpg" },
  { nome: "Sabonete em barra Macadâmia", categoria: "Sabonetes", preco: 34.90, imagem: "produto-04.jpg" },
  { nome: "Sabonete em barra Cereja e Avelã", categoria: "Sabonetes", preco: 34.90, imagem: "produto-05.jpg" },
  { nome: "Creme corporal Cereja e Avelã", categoria: "Corpo e banho", preco: 78.90, imagem: "produto-06.jpg" },
  { nome: "Sabonete em barra Cereja Negra e Praliné", categoria: "Sabonetes", preco: 34.90, imagem: "produto-07.jpg" },
  { nome: "Sabonete em barra Ameixa e Flor de Baunilha", categoria: "Sabonetes", preco: 34.90, imagem: "produto-08.jpg" },
  { nome: "Sabonete em barra Tâmara e Canela", categoria: "Sabonetes", preco: 34.90, imagem: "produto-09.jpg" },
  { nome: "Creme corporal Deleite Caramelizado", categoria: "Corpo e banho", preco: 78.90, imagem: "produto-10.jpg" },
  { nome: "Creme para as mãos Luna", categoria: "Cuidados pessoais", preco: 29.90, imagem: "produto-11.jpg" },
  { nome: "Desodorante Luna", categoria: "Cuidados pessoais", preco: 29.90, imagem: "produto-12.jpg" },
  { nome: "Esfoliante corporal Sève Amêndoas e Orquídea Negra", categoria: "Corpo e banho", preco: 39.90, imagem: "produto-13.jpg" },
  { nome: "Gel 2 em 1 para barbear e pós-barba", categoria: "Masculino", preco: 47.90, imagem: "produto-14.jpg" },
  { nome: "Tônico noturno de crescimento capilar", categoria: "Cabelos", preco: 79.90, imagem: "produto-15.jpg" },
  { nome: "Máscara fortalecedora", categoria: "Cabelos", preco: 84.90, imagem: "produto-16.jpg" },
  { nome: "214 Arabian Oasis", categoria: "Perfumes", preco: 249.90, imagem: "produto-17.jpg" },
  { nome: "Egeo Spicy Vibe", categoria: "Perfumes", preco: 164.90, imagem: "produto-18.jpg" },
  { nome: "Humor Envolve", categoria: "Perfumes", preco: 164.90, imagem: "produto-19.jpg" },
  { nome: "Luna Absoluta", categoria: "Perfumes", preco: 189.90, imagem: "produto-20.jpg" },
  { nome: "Sabonete líquido Luna Absoluta", categoria: "Corpo e banho", preco: 189.90, imagem: "produto-21.jpg" },
  { nome: "Malbec Eau de Parfum", categoria: "Perfumes", preco: 279.80, imagem: "produto-22.jpg" },
  { nome: "Batom Soul Malva da Moda", categoria: "Maquiagem", preco: 37.99, imagem: "produto-23.jpg" },
  { nome: "Batom Vermelho Paparazzi", categoria: "Maquiagem", preco: 37.99, imagem: "produto-24.jpg" },
  { nome: "Sabonete em barra Pistache", categoria: "Sabonetes", preco: 34.90, imagem: "produto-25.jpg" },
  { nome: "Sabonete em barra Caramelo Salgado", categoria: "Sabonetes", preco: 34.90, imagem: "produto-26.jpg" },
  { nome: "Creme corporal Pistache", categoria: "Corpo e banho", preco: 78.90, imagem: "produto-27.jpg" },
  { nome: "Creme corporal Caramelo Salgado", categoria: "Corpo e banho", preco: 78.90, imagem: "produto-28.jpg" },
  { nome: "Creme corporal Flor de Pêssego e Jasmim", categoria: "Corpo e banho", preco: 78.90, imagem: "produto-29.jpg" },
  { nome: "Body Splash Romã e Flor de Amora", categoria: "Body splash", preco: 96.90, imagem: "produto-30.jpg" },
  { nome: "Body Splash Caramelo Salgado", categoria: "Body splash", preco: 96.90, imagem: "produto-31.jpg" },
  { nome: "Body Splash Pistache", categoria: "Body splash", preco: 96.90, imagem: "produto-32.jpg" },
  { nome: "Desodorante em creme Macadâmia", categoria: "Cuidados pessoais", preco: 29.90, imagem: "produto-33.jpg" },
  { nome: "Egeo Choc", categoria: "Perfumes", preco: 164.90, imagem: "produto-34.jpg" },
  { nome: "Rímel Niina Secrets Super Bold", categoria: "Maquiagem", preco: "", imagem: "produto-35.jpg" }
];
