// EDITE ESTE ARQUIVO PARA ADMINISTRAR O CATÁLOGO.
// Preço vazio = "Consultar preço".
const produtos = [
  { id: 1, nome: 'Natura Tododia Óleo Bifásico Corporal Cereja e Avelã 120ml', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-01.jpg' },
  { id: 2, nome: 'O Boticário Floratta Romance de Verão', categoria: 'Perfumaria', preco: '', imagem: 'images/produto-02.jpg' },
  { id: 3, nome: 'O Boticário Egeo Dolce', categoria: 'Perfumaria', preco: '', imagem: 'images/produto-03.jpg' },
  { id: 4, nome: 'Natura Tododia Sabonete em Barra Macadâmia — 5 unidades', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-04.jpg' },
  { id: 5, nome: 'Natura Tododia Sabonete em Barra Cereja e Avelã — 5 unidades', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-05.jpg' },
  { id: 6, nome: 'Natura Tododia Creme para o Corpo Cereja e Avelã 400ml', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-06.jpg' },
  { id: 7, nome: 'Natura Tododia Sabonete em Barra Cereja e Canela — 5 unidades', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-07.jpg' },
  { id: 8, nome: 'Natura Tododia Sabonete em Barra Ameixa e Flor de Baunilha — 5 unidades', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-08.jpg' },
  { id: 9, nome: 'Natura Tododia Sabonete em Barra Cereja e Avelã — 5 unidades', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-09.jpg' },
  { id: 10, nome: 'O Boticário Cuide-se Bem Deleite Caramelizado 400ml', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-10.jpg' },
  { id: 11, nome: 'Natura Luna Creme Hidratante Perfumado para Mãos 40g', categoria: 'Cuidados Pessoais', preco: '', imagem: 'images/produto-11.jpg' },
  { id: 12, nome: 'Natura Luna Desodorante Antitranspirante Roll-on 75ml', categoria: 'Cuidados Pessoais', preco: '', imagem: 'images/produto-12.jpg' },
  { id: 13, nome: 'Natura Sève Gel Esfoliante para o Corpo 100g', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-13.jpg' },
  { id: 14, nome: 'Natura Kaiak Gel 2 em 1 para Barbear e Pós-Barba 100g', categoria: 'Masculino', preco: '', imagem: 'images/produto-14.jpg' },
  { id: 15, nome: 'Natura Produto de cuidado corporal', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-15.jpg' },
  { id: 16, nome: 'Natura Produto de cuidado corporal', categoria: 'Corpo e Banho', preco: '', imagem: 'images/produto-16.jpg' },
  { id: 17, nome: 'Produto de perfumaria', categoria: 'Perfumaria', preco: '', imagem: 'images/produto-17.jpg' },
  { id: 18, nome: 'O Boticário Egeo', categoria: 'Perfumaria', preco: '', imagem: 'images/produto-18.jpg' },
  { id: 19, nome: 'O Boticário Humor', categoria: 'Perfumaria', preco: '', imagem: 'images/produto-19.jpg' },
  { id: 20, nome: 'O Boticário Produto de perfumaria', categoria: 'Perfumaria', preco: '', imagem: 'images/produto-20.jpg' },
  { id: 21, nome: 'Eudora Siàge Ultra Bond Reset', categoria: 'Cabelos', preco: '', imagem: 'images/produto-21.jpg' },
  { id: 22, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-22.jpg' },
  { id: 23, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-23.jpg' },
  { id: 24, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-24.jpg' },
  { id: 25, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-25.jpg' },
  { id: 26, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-26.jpg' },
  { id: 27, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-27.jpg' },
  { id: 28, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-28.jpg' },
  { id: 29, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-29.jpg' },
  { id: 30, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-30.jpg' },
  { id: 31, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-31.jpg' },
  { id: 32, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-32.jpg' },
  { id: 33, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-33.jpg' },
  { id: 34, nome: 'Produto de beleza', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-34.jpg' },
  { id: 35, nome: 'Eudora Niina Secrets Super Bold — Máscara de Cílios', categoria: 'Maquiagem', preco: '', imagem: 'images/produto-35.jpg' },
];
